import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import PortfolioNavbar from '../components/navbar/portfolioNavbar'
import CustomFooter from '../components/widgets/customFooter'
import UserComponent from '../components/widgets/userComponent'
import UserStore from '../services/store/user.store'
import styles from '../styles/Home.module.css'


const userstore = new UserStore();

export default function Home() {
  const [user,setUser] = useState({})
  const getUser =() =>{
    userstore.get(3).then(response =>{
      // console.log(response);
      setUser(response)

    })
  }
  useEffect(()=>{
    getUser()
  })
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <PortfolioNavbar/> 
        <UserComponent user ={user}/>
        <CustomFooter/>
      
      
    </div>
  )
}
